- hosts: control_plane
  become: yes
  become_user: ubuntu
  user: ubuntu
  tasks:
    - name: install nginx
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml --v=5 > nginx-ingress.txt
