- hosts: control_plane
  become: yes
  become_user: ubuntu
  user: ubuntu
  tasks:
    - name: create sock-shop namespace
      command: kubectl create namespace sock-shop
      when: hostvars[inventory_hostname].ansible_host == cp_endpoint_ip

    - name: create sock-shop
      command: kubectl apply -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"
      when: hostvars[inventory_hostname].ansible_host == cp_endpoint_ip
